import Head from "next/head";
import Categories from "~/components/Categories";
import { GetServerSidePropsContext } from 'next';

export default function Home() {

  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex-center mb-16'>
        <Categories />
      </main>
    </>
  );
}
